version: '3.4'

services:
  mysql_db:
    image: mariadb:10.2
    container_name: mysql_db
    ports:
      - 3307:3306
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=root
  
  # Phpmyadmin
  mysql_pma:
    image: phpmyadmin/phpmyadmin:4.7
    container_name: mysql_pma
    ports:
      - 9090:80
    environment:
      - PMA_HOST=mysql_db